<main class="Project">

    
    <section class="Image">
        <article class="Selected_image">

            <img id="SelectedImage" src="" alt="">

        </article>

        <article class="Image_list">
            <?php foreach ($projectPictures as $picture) : ?>
                <img  src="<?= htmlspecialchars($picture->getLink()) ?>" alt="" class="Image_list_item">
            <?php endforeach; ?>
        </article>
    </section>

    <section class="Info">
        
        <?php if (isset($_SESSION["user"])) : ?>
            <a href="?page=edit&type=project&id=<?= $projectID ?>" class="btn">Edit</a>
        <?php endif; ?>
        <h1 class="Title"><?= htmlspecialchars($project->getName()) ?></h1>
        <p class="Description">
            <?= $project->getDescription() ?>
        </p>
    </section>



</main> 