<main class="Project">

    
    <section class="Image">
        <article class="Selected_image">

            <p class="error"><?= isset($error) ? $error : "" ?></p>

            <img id="SelectedImage" src="" alt="">

        </article>

        <article class="Image_list">
            <?php foreach ($projectPictures as $picture) : ?>
                <img  src="<?= htmlspecialchars($picture->getLink()) ?>" alt="" class="Image_list_item">
            <?php endforeach; ?>
        </article>
    </section>

    <section class="Info">
        
        <?php if (isset($_SESSION["user"])) : ?>
            <a href="?page=edit&type=project&id=<?= htmlspecialchars($projectID) ?>" class="btn">Edit</a>
        <?php endif; ?>

        <h1 class="Title"><?= htmlspecialchars($project->getName()) ?></h1>

        <p class="skill">
            
            <?php foreach ($projectSkills[$project->getId()] as $skill) : ?>
                <span><?= htmlspecialchars($skill->getName()) ?></span>
            <?php endforeach; ?>

        </p>
        <div>
            <?= str_replace("<script>", "&lt;script&gt;", $project->getDescription()) ?>
        </div>
    </section>



</main> 