<main class="Dashboard">

    

    <section class="Profil_info">
        <h1>Dashboard</h1>
        <form action="?page=dashboard" method="POST" enctype="multipart/form-data">
            <article>

                <h2>Mon Profil</h2>

                <label for="profil_image_input"><img src="<?= $picture->getLink() ?>" alt="Profil" id="profil_image" class="profil"></label>
                <input type="file" id="profil_image_input" name="profil_image_input" class="File_input">


            </article>

            <article>

            
                
                <label for="name">Nom</label>
                <input type="text" id="name" name="name" value="<?= $profil->getName() ?>">

                <label for="description">Description</label>
                <textarea id="description" name="description" style="display:none"><?= $profil->getDescription() ?></textarea>
                <div id="quill-editor"></div>

                <label for="email">Email</label>
                <input type="email" id="email" name="email" value="<?= $profil->getEmail() ?>">

                <label for="phone">Téléphone</label>
                <input type="tel" id="phone" name="phone" value="<?= $profil->getPhone() ?>">

                <label for="cv" class="btn">changer de CV</label>
                <p>CV actuel : <?= htmlspecialchars(explode("_", str_replace("assets/images/", "", $profil->getCv()))[1]) ?></p>
                <a href="<?= htmlspecialchars($profil->getCv()) ?>" download="<?= htmlspecialchars($profil->getName()) ?>_CV" class="btn">Voir CV</a>

                <input type="file" id="cv" name="cv" class="File_input" >

                <button type="submit" name="submit" class="btn">Modifier</button>

            

            </article>
        </form>
    </section>


    <section class="Crud">
        <h2>Item</h2>

        <article>
            <h2>
                Projects
            </h2>
            <h1><?= $projectNb ?></h1>

            <div class="link">

                <a href="?page=create&type=project">creer</a>

                <a href="?page=list&list=project">liste</a>

            </div>

        </article>

        <article>
            <h2>
                skills
            </h2>
            <h1><?= $skillNb ?></h1>

            <div class="link">

                <a href="?page=create&type=skill">creer</a>

                <a href="?page=list&list=skill">liste</a>

            </div>

        </article>

        <article>
            <h2>
                Categories
            </h2>

            <h1><?= $categoryNb ?></h1>

            <div class="link">

                <a href="?page=create&type=category">creer</a>

                <a href="?page=list&list=category">liste</a>

            </div>

        </article>





    </section>




    
</main>