<main class="Dashboard">

    

    <section class="Profil_info">
        <h1>Dashboard</h1>

        <article>

            <h2>Mon Profil</h2>

            <img src="<?= $picture->getLink() ?>" alt="Profil" class="profil">

        </article>

        <article>

            <h3><?= $profil->getName() ?></h3>

            <p><?= $profil->getDescription() ?></p>

            <p>email :<?= $profil->getEmail() ?></p>

            <p>Telephone : <?= $profil->getPhone() ?></p>

        </article>

    </section>


    <section class="Crud">
        <h2>Item</h2>

        <article>
            <h2>
                Projects
            </h2>
            <h1><?= $projectNb ?></h1>

            <div class="link">

                <a href="?page=create">creer</a>

                <a href="?page=list">liste</a>

            </div>

        </article>

        <article>
            <h2>
                skills
            </h2>
            <h1><?= $skillNb ?></h1>

            <div class="link">

                <a href="?page=create">creer</a>

                <a href="?page=list">liste</a>

            </div>

        </article>

        <article>
            <h2>
                Categories
            </h2>

            <h1><?= $categoryNb ?></h1>

            <div class="link">

                <a href="?page=create">creer</a>

                <a href="?page=list">liste</a>

            </div>

        </article>





    </section>




    
</main>