<main class="Dashboard">

    

    <section class="Profil_info">
        <h1>Dashboard</h1>

        <article>

            <h2>Mon Profil</h2>

            <img src="assets/images/profil.webp" alt="Profil" class="profil">

        </article>

        <article>

            <h3>Prenom Nom</h3>

            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Incidunt, maiores, illo similique tempora cum eveniet explicabo dolorum quaerat praesentium quidem porro velit! At illo animi non nam sequi quod ab.</p>

            <p>email :prenom.nom@example.com</p>

            <p>Telephone : 01 23 45 67 89</p>

        </article>

    </section>


    <section class="Crud">
        <h2>Item</h2>

        <article>
            <h2>
                Projects
            </h2>
            <h1>4</h1>

            <div class="link">

                <a href="?page=create">creer</a>

                <a href="?page=list">liste</a>

            </div>

        </article>

        <article>
            <h2>
                skills
            </h2>
            <h1>4</h1>

            <div class="link">

                <a href="?page=create">creer</a>

                <a href="?page=list">liste</a>

            </div>

        </article>

        <article>
            <h2>
                Categories
            </h2>

            <h1>4</h1>

            <div class="link">

                <a href="?page=create">creer</a>

                <a href="?page=list">liste</a>

            </div>

        </article>





    </section>




    
</main>