<main class="Createdit" >

    <section class="Form_createdit">

    <h1> <?= ($_GET["page"]==="create") ? "Créer" : "Modifier" ?> un projet</h1>


    <form action="?page=<?= ($_GET["page"]==="create") ? "create" : "edit" ?>" method="POST">

    <label for="title">Titre</label>
    <input type="text" id="title" name="title">

    <label for="content">Contenue</label>
    <textarea id="content" name="content"></textarea>

    <label for="category">Categories</label>
    <select name="category" id="category" required>

        <option value="" selected>--Selectioner--</option>
        <option value="1">Category 1</option>
        <option value="2">Category2</option>


    </select>
    
    <label for="skills">Compétences</label>
    <article class="Skills_Checkbox">
            
        <label class="Skills">
            <input type="checkbox" name="skills" value="HTML/CSS">HTML/CSS
        </label>

        <label class="Skills">
            <input type="checkbox" name="skills" value="JS">JS
        </label>

        <label class="Skills">
            <input type="checkbox" name="skills" value="PHP">PHP
        </label>

    </article>


    <label for="Project_Images" class="Add_Image">Ajouter des images</label>
    <input type="file" class="Project_Images" id="Project_Images" name="Project_Images" accept="image/*" multiple >

    <button type="submit" class="btn"><?= ($_GET["page"]==="create") ? "Créer" : "Modifier" ?></button>



    </form>

    </section>

    <section class="Picture">

        <h2>Picture</h2>

        <div>

            <article>

                <img src="assets/images/imagePlaceholder.jpg" alt="">
                <a href="?page=<?= ($_GET["page"]==="create") ? "create" : "edit" ?>" class="btn"> Supprimer</a>
                
            </article>

            <article>

                <img src="assets/images/imagePlaceholder.jpg" alt="">
                <a href="?page=<?= ($_GET["page"]==="create") ? "create" : "edit" ?>" class="btn"> Supprimer</a>
                
            </article>

            <article>

                <img src="assets/images/imagePlaceholder.jpg" alt="">
                
                <a href="?page=<?= ($_GET["page"]==="create") ? "create" : "edit" ?>" class="btn"> Supprimer</a>
                
            </article>

            <article>

                <img src="assets/images/imagePlaceholder.jpg" alt="">
                <a href="?page=<?= ($_GET["page"]==="create") ? "create" : "edit" ?>" class="btn"> Supprimer</a>
                
            </article>




        </div>




    </section>


</main>