<main class="Createdit" >

    <section class="Form_createdit">

    <h1> <?= ($_GET["page"]==="create") ? "Créer" : "Modifier" ?> un projet</h1>

    <p><?= isset($error) ? $error : "" ?></p>

    <form action="?page=<?= ($_GET["page"]==="create") ? "create" : "edit" ?>" method="POST" enctype="multipart/form-data">

    <label for="title">Titre</label>
    <input type="text" id="title" name="title">

    <label for="content">Contenue</label>
    <textarea id="content" name="content"></textarea>

    <label for="category">Categories</label>
    <select name="category" id="category" required>

        <option value="" selected>--Selectioner--</option>
        <?php foreach ($categories as $category) : ?>
            <option value="<?= htmlspecialchars($category->getId()) ?>"><?= htmlspecialchars($category->getName()) ?></option>
        <?php endforeach; ?>


    </select>
    
    <label for="skills">Compétences</label>
    <article class="Skills_Checkbox">

        <?php foreach ($skills as $skill) : ?>
            <label class="Skills">
                <input type="checkbox" name="skills[]" value="<?= htmlspecialchars($skill->getId()) ?>"><?= htmlspecialchars($skill->getName()) ?>
            </label>
        <?php endforeach; ?>

    </article>


    <label for="Project_Images" class="Add_Image">Ajouter des images</label>
    <input type="file" class="Project_Images" id="Project_Images" name="Project_Images[]" accept="image/*" multiple >

    <button type="submit" name="submit" class="btn"><?= ($_GET["page"]==="create") ? "Créer" : "Modifier" ?></button>



    </form>

    

    </section>

    <section class="Picture">

        <h2>Pictures</h2>

        <div id="picture-preview">

        </div>

    </section>


</main>