<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= htmlspecialchars($title); ?></title>
    <link rel="stylesheet" href="assets/css/style.css">
    <script src="assets/js/script.js" defer></script>
    <?php $jsPage = "assets/js/" . htmlspecialchars($_GET["page"] ?? "home") . ".js"; ?>
    <?php if (file_exists($jsPage)): ?>
        <script src="<?= $jsPage ?>" defer></script>
    <?php endif; ?>
</head>
<body>

    <header>
        <div class="Container">
            <a href="?page=home"><h1><?= htmlspecialchars($layoutName); ?></h1></a>

            <?php if (!empty($_SESSION["user"])): ?>
                <div class="Btn_Container">
                    <a href="?page=dashboard" class="btn">Dashboard</a>
                    <a href="?page=logout" class="btn">Déconnexion</a>
                </div>
            <?php else: ?>
                <a href="?page=login" class="btn">Connexion</a>
            <?php endif; ?>


        </div>
    </header>

    <?php include $content; ?>
    
    <footer>

        <p>&copy; <?= htmlspecialchars($layoutName); ?> | 2026</p>
        
    </footer>

</body>
</html>