<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $title; ?></title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="text/javascript" href="assets/js/script.js" defer>
</head>
<body>

    <header>
        <div>
            <a href="?page=home"><h1>Prenom Nom</h1></a>

            <a href="?page=login" class="btn">connexion</a>
        </div>
    </header>

    <?php include $content; ?>
    
    <footer>

        <p>&copy; Prenom Nom | 2026</p>
        
    </footer>

</body>
</html>