<main class="Login">

    <section class="Login_form">

        <h1>Connexion</h1>

        <form action="?page=login" method="POST">

            <label for="name">Nom :</label>
            
            <input type="text" id="name" name="name" required>
            

            <label for="password">Mot de passe :</label>
            
            <input type="password" id="password" name="password" required>

            <button type="submit" name="submit" class="btn">Se connecter</button>

            <p class="Error"><?=  !empty($error) ? $error : '' ?></p>

        </form>

    </section>
    
</main>