<main class="Home">

    <section class="Intro">

        
            <article class="Title">
                <h1>Mon Portfolio</h1>
                <h2>Prenom Nom Developer web</h2>
            </article>

            <article class="Presentation">
                <img src="assets/images/profil.webp" alt="Photo de Profil" class="Home__photo">
                <p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Id aperiam eveniet quo cum veritatis sequi fuga! Unde quibusdam, culpa illo possimus ea tempore? Necessitatibus quis eligendi tenetur voluptatibus numquam neque commodi facere reprehenderit, amet maxime cupiditate eius animi et. Id harum ipsa perferendis officia dolor, esse velit commodi. Nemo autem officiis praesentium sunt! Veritatis saepe aut fuga sed, exercitationem pariatur nulla accusantium voluptatum quis totam dolore possimus laudantium fugiat voluptatibus ex laborum, dolorem magnam ipsum distinctio repellat ab! Harum sed, incidunt quisquam placeat amet accusamus dolorem fugit dolorum esse quo! Soluta, laborum perferendis! Adipisci error in ea quos pariatur iste.
                </p>
            </article>

            <article class="CV">

            <h2>Consulter mon Curriculum Vitae</h2>
            <a href="assets/images/CV.pdf" download="Prenom_Nom_CV" class="btn">Télécharger</a>

            </article>
        

    </section>

    <section class="Projects">

        <h1>Mes Projets</h1>

        <div class="Projects_list">

            <article class="Project">
                <img src="assets/images/imagePlaceholder.jpg" alt="" class="Project_image">
                <h3>Projet 1</h3>
                <p>Categorie : Portfolio</p>
                <h3>Compétences :</h3>
                <p><span>HTML</span> <span>CSS</span> <span>JavaScript</span></p>
                <a href="?page=project" class="btn">Découvrir</a>
            </article>

            <article class="Project">
                <img src="assets/images/imagePlaceholder.jpg" alt="" class="Project_image">
                <h3>Projet 2</h3>
                <p>Categorie : Portfolio</p>
                <h3>Compétences :</h3>
                <p><span>HTML</span> <span>CSS</span> <span>JavaScript</span></p>
                <a href="?page=project" class="btn">Découvrir</a>
            </article>

            <article class="Project">
                <img src="assets/images/imagePlaceholder.jpg" alt="" class="Project_image">
                <h3>Projet 3</h3>
                <p>Categorie : Portfolio</p>
                <h3>Compétences :</h3>
                <p><span>HTML</span> <span>CSS</span> <span>JavaScript</span></p>
                <a href="?page=project" class="btn">Découvrir</a>
            </article>

            <article class="Project">
                <img src="assets/images/imagePlaceholder.jpg" alt="" class="Project_image">
                <h3>Projet 4</h3>
                <p>Categorie : Portfolio</p>
                <h3>Compétences :</h3>
                <p><span>HTML</span> <span>CSS</span> <span>JavaScript</span></p>
                <a href="?page=project" class="btn">Découvrir</a>
            </article>


        </div>
    


    </section>
    
    <section class="Coordonnées">

        <h1>Mes Coordonnées</h1>

        <article>

            <a href="mailto:exemple@email.com" class="btn">exemple@email.com</a>

            <a href="tel:+33612345678" class="btn">06 12 34 56 78</a>

        </article>
    </section>


</main>