<main class="Home">

    <section class="Intro">

        
            <article class="Title">
                <h1>Mon Portfolio</h1>
                <h2><?= htmlspecialchars($profil->getName()) ?> Developer web</h2>
            </article>

            <article class="Presentation">
                <img src="<?= htmlspecialchars($picture->getLink()) ?>" alt="Photo de <?= htmlspecialchars($profil->getName()) ?>" class="Home__photo">
                <div>
                    <p>
                        <?= str_replace("<script>", "&lt;script&gt;", $profil->getDescription()) ?>
                    </p>
                </div>
            </article>

            <article class="CV">

            <h2 id="TitreCV">Consulter mon Curriculum Vitae</h2>
            <a href="<?= $profil->getCv() ?>" download="<?= $profil->getName() ?>_CV" class="btn">Télécharger</a>

            </article>
        

    </section>

    <section class="Projects">

        <h1>Mes Projets</h1>

        <div class="Projects_list">

            <?php foreach ($projects as $project) : ?>

                <article class="Project">

                    <img src="<?= !empty($projectPictures[$project->getId()]) ? htmlspecialchars($projectPictures[$project->getId()]->getLink()) : '' ?>" alt="" class="Project_image">
                    <h3><?= htmlspecialchars($project->getName()) ?></h3>
                    <h3>Categorie</h3>
                    <p>
                        <?php foreach ($projectCategories[$project->getId()] as $category) : ?>
                            <span><?= htmlspecialchars($category->getName()) ?></span>

                        <?php endforeach; ?>
                    </p>
                    <h3>Compétences</h3>
                    <p>
                        <?php foreach ($projectSkills[$project->getId()] as $skill) : ?>
                            <span><?= htmlspecialchars($skill->getName()) ?></span>
                        <?php endforeach; ?>
                    </p>


                    <a href="?page=project&id=<?= $project->getId() ?>" class="btn">Découvrir</a>

                </article>

            <?php endforeach; ?>

        </div>
    


    </section>
    
    <section class="Coordonnées">

        <h1>Mes Coordonnées</h1>

        <article>

            <a href="mailto:<?= $profil->getEmail() ?>" class="btn"><?= $profil->getEmail() ?></a>

            <a href="tel:<?= $profil->getPhone() ?>" class="btn"><?= $profil->getPhone() ?></a>

        </article>
    </section>


</main>