<main class="Home">

    <section class="Intro">

        
            <article class="Title">
                <h1>Mon Portfolio</h1>
                <h2><?= $profil->getName() ?> Developer web</h2>
            </article>

            <article class="Presentation">
                <img src="<?= $picture->getLink() ?>" alt="Photo de <?= $profil->getName() ?>" class="Home__photo">
                <p>
                    <?= $profil->getDescription() ?>
                </p>
            </article>

            <article class="CV">

            <h2>Consulter mon Curriculum Vitae</h2>
            <a href="<?= $profil->getCv() ?>" download="<?= $profil->getName() ?>_CV" class="btn">Télécharger</a>

            </article>
        

    </section>

    <section class="Projects">

        <h1>Mes Projets</h1>

        <div class="Projects_list">

            <?php foreach ($projects as $project) : ?>

                <article class="Project">

                    <img src="<?= !empty($projectPictures[$project->getId()]) ? htmlspecialchars($projectPictures[$project->getId()]->getLink()) : '' ?>" alt="" class="Project_image">
                    <h3><?= htmlspecialchars($project->getName()) ?></h3>
                    <p>Categorie : Portfolio</p>
                    <h3>Compétences :</h3>
                    <p></p>
                    <a href="?page=project&id=<?= $project->getId() ?>" class="btn">Découvrir</a>

                </article>

            <?php endforeach; ?>

        </div>
    


    </section>
    
    <section class="Coordonnées">

        <h1>Mes Coordonnées</h1>

        <article>

            <a href="mailto:<?= $profil->getEmail() ?>" class="btn"><?= $profil->getEmail() ?></a>

            <a href="tel:<?= $profil->getPhone() ?>" class="btn"><?= $profil->getPhone() ?></a>

        </article>
    </section>


</main>