<main class="List">

    <section>
        <h1>Liste</h1>

        <div class="Title-Container">
            <h2>Projets</h2>
            <a href="?page=create" class="btn">Créer</a>
        </div>



        <article class="Object">
            <img src="assets/images/imagePlaceholder.jpg" alt="">
            <h4>Project Title</h4>
            <p> <span>Category 1</span> <span>Category 2</span></p>
            <div>
                <a href="?page=project" class="btn">voir</a>
                <a href="?page=edit" class="Edit">Modifier</a>
                <a href="?page=list" class="Delete">Supprimer</a>
            </div>

        </article>

        <article class="Object">
            <img src="assets/images/imagePlaceholder.jpg" alt="">
            <h4>Project Title</h4>
            <p> <span>Category 1</span> <span>Category 2</span></p>
            <div>
                <a href="?page=project" class="btn">voir</a>
                <a href="?page=edit" class="Edit">Modifier</a>
                <a href="?page=list" class="Delete">Supprimer</a>
            </div>

        </article>

        <article class="Object">
            <img src="assets/images/imagePlaceholder.jpg" alt="">
            <h4>Project Title</h4>
            <p> <span>Category 1</span> <span>Category 2</span></p>
            <div>
                <a href="?page=project" class="btn">voir</a>
                <a href="?page=edit" class="Edit">Modifier</a>
                <a href="?page=list" class="Delete">Supprimer</a>
            </div>

        </article>







    </section>
    
</main>