<main class="List">

    <section>
        <h1>Liste</h1>


        <?php switch ($_GET["list"]) : case "project": ?>

        <div class="Title-Container">
            <h2>Projets</h2>
            <a href="?page=create&type=project" class="btn">Créer</a>
        </div>


        <?php foreach ($projects as $project) : ?>
            <article class="Object">
                <?php if (!empty($pictures[$project->getId()])): ?>
                    <img src="<?= htmlspecialchars($pictures[$project->getId()]->getLink()) ?>" alt="">
                <?php endif; ?>
                <h3><?= htmlspecialchars($project->getName()) ?></h3>
                <p>
                    
                    <?php if (isset($categories[$project->getIdCategory()])): ?>
                        <span><?= htmlspecialchars($categories[$project->getIdCategory()]->getName()) ?></span>
                    <?php endif; ?>
                </p>
                <div>
                    <a href="?page=project&list=project&id=<?= htmlspecialchars($project->getId()) ?>" class="btn">voir</a>
                    <a href="?page=edit&type=project&id=<?= htmlspecialchars($project->getId()) ?>" class="Edit">Modifier</a>
                    <a href="?page=list&list=project&delete=<?= htmlspecialchars($project->getId()) ?>" class="Delete">Supprimer</a>
                </div>

            </article>
        <?php endforeach; ?>

        <?php break; ?>


        <?php case "category": ?>
            <div class="Title-Container">
                <h2>Catégories</h2>
                <a href="?page=create&type=category" class="btn">Créer</a>
            </div>




            <?php break; ?>




        <?php case "skill": ?>
            <div class="Title-Container">
                <h2>Compétences</h2>
                <a href="?page=create&type=skill" class="btn">Créer</a>
            </div>



            <?php break; ?>






        <?php default: ?>
            <?php header("Location: /?page=dashboard"); ?>
            <?php exit(); ?>
        <?php endswitch; ?>



    </section>
    
</main>